In [3]:
import numpy as np

In [4]:
# each tile has a base treasure of 7500

# prop = (expeditions that selected tile x / total number of selected expeditions) * 100
# treasure = (base_treasure * multiplier) / (hunters + prop)
# reward = treasure - expedition_cost

# expedition cost (max 3): 0, 25k, 75k

In [26]:
multiplier = np.array([[24, 70, 41, 21, 60],
                       [47, 82, 87, 80, 35],
                       [73, 89, 100, 90, 17],
                       [77, 83, 85, 79, 55],
                       [12, 27, 52, 15, 30]])

hunters = np.array([[2, 4, 3, 2, 4],
                    [3, 5, 5, 5, 3],
                    [4, 5, 8, 7, 2],
                    [5, 5, 5, 5, 4],
                    [2, 3, 4, 2, 3]])

def treasure(prop):
    t = (7500 * multiplier) / (hunters + prop)
    with np.printoptions(precision=4, suppress=True, formatter={'float': '{:0.1f}'.format}, linewidth=200):
        print(t)
        print('\n')


In [34]:
treasure(0)
treasure(5)
treasure(10)
treasure(15)
treasure(20)
treasure(30)

[[90000.0 131250.0 102500.0 78750.0 112500.0]
 [117500.0 123000.0 130500.0 120000.0 87500.0]
 [136875.0 133500.0 93750.0 96428.6 63750.0]
 [115500.0 124500.0 127500.0 118500.0 103125.0]
 [45000.0 67500.0 97500.0 56250.0 75000.0]]


[[25714.3 58333.3 38437.5 22500.0 50000.0]
 [44062.5 61500.0 65250.0 60000.0 32812.5]
 [60833.3 66750.0 57692.3 56250.0 18214.3]
 [57750.0 62250.0 63750.0 59250.0 45833.3]
 [12857.1 25312.5 43333.3 16071.4 28125.0]]


[[15000.0 37500.0 23653.8 13125.0 32142.9]
 [27115.4 41000.0 43500.0 40000.0 20192.3]
 [39107.1 44500.0 41666.7 39705.9 10625.0]
 [38500.0 41500.0 42500.0 39500.0 29464.3]
 [7500.0 15576.9 27857.1 9375.0 17307.7]]


[[10588.2 27631.6 17083.3 9264.7 23684.2]
 [19583.3 30750.0 32625.0 30000.0 14583.3]
 [28815.8 33375.0 32608.7 30681.8 7500.0]
 [28875.0 31125.0 31875.0 29625.0 21710.5]
 [5294.1 11250.0 20526.3 6617.6 12500.0]]


[[8181.8 21875.0 13369.6 7159.1 18750.0]
 [15326.1 24600.0 26100.0 24000.0 11413.0]
 [22812.5 26700.0 26785.7 25000.0 57

Top 5 treasure spots (based on prop=0):
- C1, C2, A2, B3, D3

High level thoughts:
- How much does prop affect reward?
    - 10% prop reduces reward by a factor of about 3.5 based on hunter mean being 4
- How much will prop be at the 'hotspots'?
- How many participants will consider these factors and apply the opposite strategy?
    - Based on the leaderboard so far, most groups seem to be making rational decisions.
- How many expeditions to make, and how many will others make?
- 15 options: if participants make 2 expeditions on average and pick randomly, expected prop for each expedition is ~13.3%? How will this vary based on expected treasure?
- It is difficult to justify making 3 expeditions.



### Submission:
(position labels on the provided map are different)

- B2 (H26)
- C4 (J29)